### ISSUE TITLE
AUR packages

### ISSUE THREAD

**Issue by orhun** [adamsky/cns#12]
Hey! Nice project.

I'd like to tell you that I created the following packages for installation of `cns` on Arch Linux:

* [cns](https://aur.archlinux.org/packages/cns/)
* [cns-git](https://aur.archlinux.org/packages/cns-git/)

I can propose a PR for adding installation instructions to README.md if you like.

**Comment by adamsky** [comment]
Thanks, glad you find it useful!

Adding `cns` to AUR sounds great, though it definitely is kinda early stage and needs more love. Adding instructions is fine by me.
